version: '3.1'

services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - MYSQL_ROOT_PASSWORD=123123
            - MYSQL_USER=root
            - MYSQL_PASSWORD=123123
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=123123
            - MYSQL_DATABASE=shop
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
volumes:
    mysql-data:
